import pptxgen from 'pptxgenjs';
import type { Session, Slide as DbSlide } from './db';

interface ThemeConfig {
  bg: string;
  titleColor: string;
  textColor: string;
  accentColor: string;
  cardBg: string;
  codeBg: string;
  codeColor: string;
  borderGlow: string;
}

const THEMES: Record<'dark' | 'blue' | 'light', ThemeConfig> = {
  dark: {
    bg: '0F172A',         // Slate 900
    titleColor: 'C084FC', // Purple 400
    textColor: 'E2E8F0',  // Slate 200
    accentColor: '06B6D4', // Cyan 500
    cardBg: '1E293B',     // Slate 800
    codeBg: '020617',     // Slate 950
    codeColor: '38BDF8',  // Sky 400
    borderGlow: '334155'  // Slate 700
  },
  blue: {
    bg: '0B2545',         // Dark blue
    titleColor: '60A5FA', // Blue 400
    textColor: 'EEF4F8',  // Very light blue-gray
    accentColor: '34D399', // Emerald 400
    cardBg: '134074',     // Medium blue
    codeBg: '081F37',     // Deepest blue
    codeColor: 'A7F3D0',  // Emerald 100
    borderGlow: '1E6091'  // Blue accent
  },
  light: {
    bg: 'FFFFFF',         // White
    titleColor: '7C3AED', // Purple 600
    textColor: '1F2937',  // Gray 800
    accentColor: '0891B2', // Cyan 600
    cardBg: 'F3F4F6',     // Gray 100
    codeBg: '111827',     // Gray 900
    codeColor: '34D399',  // Emerald 400
    borderGlow: 'D1D5DB'  // Gray 300
  }
};

export async function generatePPT(session: Session, themeName: 'dark' | 'blue' | 'light' = 'dark'): Promise<void> {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';
  
  const theme = THEMES[themeName];
  
  // Set global slides author metadata
  pptx.author = 'LecturaAI';
  pptx.company = 'LecturaAI Platform';
  pptx.subject = session.subject;
  pptx.title = session.title;

  // Helper function to set slide background
  const applyBackground = (slide: pptxgen.Slide) => {
    slide.background = { fill: theme.bg };
  };

  // 1. TITLE SLIDE
  const titleSlide = pptx.addSlide();
  applyBackground(titleSlide);
  
  // Decorative Accent Shape
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 0.4,
    h: 5.625,
    fill: { color: theme.accentColor }
  });

  // Logo / Header
  titleSlide.addText('LECTURA AI • GENERATED PRESENTATION', {
    x: 0.8,
    y: 0.8,
    w: 11.0,
    h: 0.4,
    fontSize: 12,
    bold: true,
    color: theme.accentColor,
    fontFace: 'Arial'
  });

  // Presentation Title
  titleSlide.addText(session.title, {
    x: 0.8,
    y: 1.6,
    w: 11.0,
    h: 1.8,
    fontSize: 40,
    bold: true,
    color: theme.textColor,
    fontFace: 'Arial'
  });

  // Subtitle / Course Subject
  titleSlide.addText(`Course/Subject: ${session.subject}`, {
    x: 0.8,
    y: 3.4,
    w: 11.0,
    h: 0.4,
    fontSize: 18,
    italic: true,
    color: theme.titleColor,
    fontFace: 'Arial'
  });

  // Session metadata
  const formattedDate = new Date(session.createdAt).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  const durationMin = Math.round(session.duration / 60);
  
  titleSlide.addText(`Date: ${formattedDate}\nDuration: ~${durationMin} minutes`, {
    x: 0.8,
    y: 4.2,
    w: 5.0,
    h: 0.8,
    fontSize: 12,
    color: theme.textColor,
    fontFace: 'Arial'
  });

  // Footer Branding
  titleSlide.addText('Generated by LecturaAI Classroom Recording Engine', {
    x: 0.8,
    y: 5.1,
    w: 11.0,
    h: 0.3,
    fontSize: 10,
    color: theme.textColor,
    transparency: 50,
    fontFace: 'Arial'
  });

  // 2. AGENDA SLIDE
  const agendaSlide = pptx.addSlide();
  applyBackground(agendaSlide);

  agendaSlide.addText('Session Agenda & Topics', {
    x: 0.8,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 24,
    bold: true,
    color: theme.titleColor,
    fontFace: 'Arial'
  });

  // Create columns of topics
  const topicsToShow = session.topics.slice(0, 6);
  topicsToShow.forEach((topic, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const xPos = 0.8 + col * 5.8;
    const yPos = 1.4 + row * 1.3;

    // Index Number box
    agendaSlide.addShape(pptx.ShapeType.roundRect, {
      x: xPos,
      y: yPos,
      w: 0.6,
      h: 0.6,
      fill: { color: theme.cardBg },
      line: { color: theme.accentColor, width: 1 }
    });

    agendaSlide.addText(`${index + 1}`, {
      x: xPos,
      y: yPos,
      w: 0.6,
      h: 0.6,
      fontSize: 16,
      bold: true,
      color: theme.accentColor,
      align: 'center',
      valign: 'middle',
      fontFace: 'Arial'
    });

    // Topic title & description
    agendaSlide.addText([
      { text: `[${topic.time}] ${topic.title}\n`, options: { bold: true, color: theme.textColor, fontSize: 14 } },
      { text: topic.description, options: { color: theme.textColor, fontSize: 11, transparency: 30 } }
    ], {
      x: xPos + 0.8,
      y: yPos - 0.1,
      w: 4.8,
      h: 1.0,
      fontFace: 'Arial'
    });
  });

  // 3. CORE CONTENT SLIDES
  session.slides.forEach((slideData: DbSlide) => {
    if (slideData.type === 'title') return; // Skip title slide as we built custom title
    
    const slide = pptx.addSlide();
    applyBackground(slide);

    // Slide Header
    slide.addText(slideData.title, {
      x: 0.8,
      y: 0.6,
      w: 11.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: theme.titleColor,
      fontFace: 'Arial'
    });

    // Speaker Notes (if any)
    if (slideData.notes) {
      slide.addNotes(slideData.notes);
    }

    // Embed Screenshot if slide is visual or has image reference
    let hasImage = false;
    let screenshotBase64 = '';
    
    if (slideData.image) {
      hasImage = true;
      screenshotBase64 = slideData.image;
    } else if (slideData.type === 'visual' && session.screenshots.length > 0) {
      // Pick a screenshot closest to slide number mapping
      const index = Math.min(slideData.slideNumber % session.screenshots.length, session.screenshots.length - 1);
      hasImage = true;
      screenshotBase64 = session.screenshots[index].dataUrl;
    }

    // Format Image String for pptxgenjs
    if (hasImage && screenshotBase64.startsWith('data:')) {
      screenshotBase64 = screenshotBase64.split(',')[1];
    }

    // Render by slide type
    if (slideData.type === 'code') {
      // CODE BLOCK LAYOUT: Text left, code right
      // Bullet points
      slide.addText(
        slideData.content.map(point => ({ text: `• ${point}\n\n`, options: { fontSize: 13, color: theme.textColor } })),
        {
          x: 0.8,
          y: 1.4,
          w: 5.2,
          h: 3.6,
          fontFace: 'Arial'
        }
      );

      // Code background card
      slide.addShape(pptx.ShapeType.roundRect, {
        x: 6.4,
        y: 1.4,
        w: 5.8,
        h: 3.6,
        fill: { color: theme.codeBg },
        line: { color: theme.borderGlow, width: 1 }
      });

      // Code Text
      slide.addText(slideData.codeBlock || '// Sample Code Block', {
        x: 6.6,
        y: 1.6,
        w: 5.4,
        h: 3.2,
        fontSize: 11,
        color: theme.codeColor,
        fontFace: 'Courier New',
        valign: 'top'
      });

    } else if (hasImage) {
      // VISUAL LAYOUT: Bullets left, screenshot right
      // Bullet points
      slide.addText(
        slideData.content.map(point => ({ text: `• ${point}\n\n`, options: { fontSize: 13, color: theme.textColor } })),
        {
          x: 0.8,
          y: 1.4,
          w: 5.2,
          h: 3.6,
          fontFace: 'Arial'
        }
      );

      // Add screenshot image
      try {
        slide.addImage({
          data: 'base64,' + screenshotBase64,
          x: 6.4,
          y: 1.4,
          w: 5.8,
          h: 3.26 // Maintain ~16:9 aspect ratio (5.8w / 3.26h = 1.77)
        });

        slide.addText('Screenshot extracted from session', {
          x: 6.4,
          y: 4.75,
          w: 5.8,
          h: 0.25,
          fontSize: 9,
          italic: true,
          color: theme.textColor,
          transparency: 40,
          align: 'center',
          fontFace: 'Arial'
        });
      } catch (err) {
        console.error('Error adding slide image:', err);
        // Fallback card if image failing
        slide.addShape(pptx.ShapeType.rect, { x: 6.4, y: 1.4, w: 5.8, h: 3.26, fill: { color: theme.cardBg } });
        slide.addText('[Captured Class Visual Panel]', { x: 6.4, y: 2.8, w: 5.8, h: 0.5, color: theme.textColor, align: 'center', fontFace: 'Arial' });
      }

    } else {
      // STANDARD BULLET POINTS LAYOUT
      slide.addText(
        slideData.content.map(point => ({ text: `• ${point}\n\n`, options: { fontSize: 16, color: theme.textColor } })),
        {
          x: 0.8,
          y: 1.4,
          w: 11.4,
          h: 3.6,
          fontFace: 'Arial'
        }
      );
    }

    // Slide Number Indicator
    slide.addText(`Slide ${slideData.slideNumber}`, {
      x: 11.2,
      y: 5.2,
      w: 1.5,
      h: 0.3,
      fontSize: 10,
      color: theme.textColor,
      transparency: 50,
      align: 'right',
      fontFace: 'Arial'
    });
  });

  // 4. SPEAKER STATS SLIDE
  if (session.speakers && session.speakers.length > 0) {
    const statsSlide = pptx.addSlide();
    applyBackground(statsSlide);

    statsSlide.addText('Speaker Activity & Tracking Summary', {
      x: 0.8,
      y: 0.6,
      w: 11.0,
      h: 0.6,
      fontSize: 24,
      bold: true,
      color: theme.titleColor,
      fontFace: 'Arial'
    });

    statsSlide.addText('Voice footprint and lecture interaction tracking:', {
      x: 0.8,
      y: 1.3,
      w: 11.0,
      h: 0.3,
      fontSize: 13,
      color: theme.textColor,
      transparency: 20,
      fontFace: 'Arial'
    });

    // Render list of speakers as visual rows
    session.speakers.forEach((speaker, idx) => {
      const yPos = 1.8 + idx * 0.9;
      const totalDuration = session.duration || 1;
      const pct = Math.round((speaker.duration / totalDuration) * 100);

      // Speaker Name
      statsSlide.addText(`${speaker.name}`, {
        x: 0.8,
        y: yPos,
        w: 2.0,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: theme.textColor,
        fontFace: 'Arial'
      });

      // Progress bar background
      statsSlide.addShape(pptx.ShapeType.rect, {
        x: 3.0,
        y: yPos + 0.1,
        w: 6.0,
        h: 0.25,
        fill: { color: theme.cardBg },
        line: { color: theme.textColor, width: 0.5, transparency: 80 }
      });

      // Progress bar fill
      const fillW = Math.max(0.1, 6.0 * (speaker.duration / totalDuration));
      statsSlide.addShape(pptx.ShapeType.rect, {
        x: 3.0,
        y: yPos + 0.1,
        w: fillW,
        h: 0.25,
        fill: { color: speaker.color.replace('#', '') }
      });

      // Percentage and duration
      const minutes = Math.floor(speaker.duration / 60);
      const seconds = speaker.duration % 60;
      const formattedTime = `${minutes}m ${seconds}s`;
      
      statsSlide.addText(`${pct}%  (${formattedTime})`, {
        x: 9.2,
        y: yPos,
        w: 3.0,
        h: 0.5,
        fontSize: 13,
        bold: true,
        color: theme.accentColor,
        fontFace: 'Arial'
      });
    });
  }

  // 5. SUMMARY SLIDE
  const summarySlide = pptx.addSlide();
  applyBackground(summarySlide);

  summarySlide.addText('Key Takeaways & Summary', {
    x: 0.8,
    y: 0.6,
    w: 11.0,
    h: 0.6,
    fontSize: 24,
    bold: true,
    color: theme.titleColor,
    fontFace: 'Arial'
  });

  // Left panel: Structured points
  summarySlide.addText(
    session.keyPoints.slice(0, 4).map(point => ({ text: `• ${point}\n\n`, options: { fontSize: 13, color: theme.textColor } })),
    {
      x: 0.8,
      y: 1.4,
      w: 6.0,
      h: 3.6,
      fontFace: 'Arial'
    }
  );

  // Right panel: Glass card of overall summary text
  summarySlide.addShape(pptx.ShapeType.roundRect, {
    x: 7.2,
    y: 1.4,
    w: 5.0,
    h: 3.4,
    fill: { color: theme.cardBg },
    line: { color: theme.accentColor, width: 1 }
  });

  summarySlide.addText([
    { text: 'Lecture Summary Note:\n\n', options: { bold: true, color: theme.titleColor, fontSize: 14 } },
    { text: session.summary, options: { color: theme.textColor, fontSize: 11, lineSpacing: 16 } }
  ], {
    x: 7.4,
    y: 1.6,
    w: 4.6,
    h: 3.0,
    fontFace: 'Arial'
  });

  // Save/Download the File
  const cleanTitle = session.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  await pptx.writeFile({ fileName: `${cleanTitle}_slides.pptx` });
}
